### ISSUE TITLE
feat(cli): magnet filter

### ISSUE THREAD

**Issue by yjl9903** [XLorPaste/AnimePaste#216]
## Motivation

Filter unexpected magnet resource.

For example, you dont want videos tagged with 'zh-Hant', 'HEVC', and so on.

## Config

```
# ~/.animepaste/config.yaml

filter:
  title: # some RegExp
    - '...'
  tags:
    include:
      - '1080'
    exclude:
      - 'HEVC'
      - '720'
```
