### ISSUE TITLE
feat(cli): hooks plugin

### ISSUE THREAD

**Issue by yjl9903** [XLorPaste/AnimePaste#217]
## Motivation

1. Support Push custom notification
2. Sync database
3. ...

## Config

```yaml
# ~/.animepaste/config.yaml

hooks:
  watch:
    pre: '...'
    post: '...'
```
